
import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Tất cả', icon: '🔥' },
  { id: 'tech', name: 'Điện tử', icon: '💻' },
  { id: 'fashion', name: 'Thời trang', icon: '👕' },
  { id: 'home', name: 'Gia dụng', icon: '🏠' },
  { id: 'beauty', name: 'Làm đẹp', icon: '💄' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Tai nghe Bluetooth Marshall Major IV - Chính hãng',
    image: 'https://picsum.photos/seed/marshall/500/500',
    originalPrice: 4500000,
    discountPrice: 3250000,
    label: 'Deal hot',
    category: 'tech',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '2',
    name: 'Máy pha cà phê Espresso mini 20 Bar',
    image: 'https://picsum.photos/seed/coffee/500/500',
    originalPrice: 2100000,
    discountPrice: 1590000,
    label: 'Bán chạy',
    category: 'home',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '3',
    name: 'Áo khoác Bomber Unisex Local Brand',
    image: 'https://picsum.photos/seed/bomber/500/500',
    originalPrice: 650000,
    discountPrice: 399000,
    label: 'Giảm sâu',
    category: 'fashion',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '4',
    name: 'Bàn phím cơ không dây NuPhy Air75 V2',
    image: 'https://picsum.photos/seed/keyboard/500/500',
    originalPrice: 3200000,
    discountPrice: 2850000,
    label: 'Deal hot',
    category: 'tech',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '5',
    name: 'Nồi chiên không dầu Philips HD9270/91 6.2L',
    image: 'https://picsum.photos/seed/airfryer/500/500',
    originalPrice: 4200000,
    discountPrice: 2490000,
    label: 'Giảm sâu',
    category: 'home',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '6',
    name: 'Serum Estee Lauder Advanced Night Repair 50ml',
    image: 'https://picsum.photos/seed/serum/500/500',
    originalPrice: 3500000,
    discountPrice: 2150000,
    label: 'Bán chạy',
    category: 'beauty',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '7',
    name: 'Chuột Logitech MX Master 3S Wireless',
    image: 'https://picsum.photos/seed/mouse/500/500',
    originalPrice: 2800000,
    discountPrice: 2200000,
    label: 'Deal hot',
    category: 'tech',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '8',
    name: 'Giày Sneaker Nike Air Force 1 07 White',
    image: 'https://picsum.photos/seed/shoes/500/500',
    originalPrice: 2900000,
    discountPrice: 2450000,
    label: 'Bán chạy',
    category: 'fashion',
    affiliateUrl: 'https://shopee.vn/',
  },
  {
    id: '9',
    name: 'Son Kem Lì Black Rouge Air Fit Velvet Tint',
    image: 'https://picsum.photos/seed/lipstick/500/500',
    originalPrice: 250000,
    discountPrice: 145000,
    label: 'Giảm sâu',
    category: 'beauty',
    affiliateUrl: 'https://shopee.vn/',
  },
];
